import { registerBehaviourClass, AnimationRenderer, AudioBehaviour, Binding, BitmapRenderer, BoxCollider, Camera, CapsuleCollider, CircleCollider, EdgeCollider, PhysicsWorld, RigidBody, ShapeRectRenderer, TextRenderer, Transform, GameEngine } from "../lib/mygameengine";
import { Attackable } from "./behaviours/Attackable";
import { DiedMenuStateMachine } from "./behaviours/DiedMenuStateMachine";
import { Enemy } from "./behaviours/Enemy";
import { Enemy1 } from "./behaviours/Enemy1";
import { Enemy1HealthStateMachine } from "./behaviours/Enemy1HealthStateMachine";
import { Enemy2 } from "./behaviours/Enemy2";
import { Enemy2HealthStateMachine } from "./behaviours/Enemy2HealthStateMachine";
import { Enemy3 } from "./behaviours/Enemy3";
import { Enemy3HealthStateMachine } from "./behaviours/Enemy3HealthStateMachine";
import { Enemy4 } from "./behaviours/Enemy4";
import { Enemy4HealthStateMachine } from "./behaviours/Enemy4HealthStateMachine";
import { Enemy5 } from "./behaviours/Enemy5";
import { Enemy5HealthStateMachine } from "./behaviours/Enemy5HealthStateMachine";
import { Enemy6 } from "./behaviours/Enemy6";
import { Enemy6HealthStateMachine } from "./behaviours/Enemy6HealthStateMachine";
import { EnemyHealthStateMachine } from "./behaviours/EnemyHealthStateMachine";
import { GameManager } from "./behaviours/GameManager";
import { HealthStateMachine } from "./behaviours/HealthState";
import { MainMenuStateMachine } from "./behaviours/MainMenuState";
import { ManaStateMachine } from "./behaviours/ManaState";
import { PauseMenuStateMachine } from "./behaviours/PauseMenuStateMachine";
import { StarCollisionHandler } from "./behaviours/StarCollisionHandler";
import { Walkable } from "./behaviours/Walkable";
import { BlockPrefabBinding } from "./bindings/BlockPrefabBinding";
import { Enemy1PrefabBinding } from "./bindings/Enemy1PrefabBinding";
import { Enemy2PrefabBinding } from "./bindings/Enemy2PrefabBinding";
import { Enemy3PrefabBinding } from "./bindings/Enemy3PrefabBinding";
import { Enemy4PrefabBinding } from "./bindings/Enemy4PrefabBinding";
import { Enemy5PrefabBinding } from "./bindings/Enemy5PrefabBinding";
import { Enemy6PrefabBinding } from "./bindings/Enemy6PrefabBinding";
import { EnemyPrefabBinding } from "./bindings/EnemyPrefabBinding";
import { MainRolePrefabBinding } from "./bindings/MainRolePrefabBinding";
import { MaoQiPrefabBinding } from "./bindings/MaoQiPrefabBinding";
import { WallPrefabBinding } from "./bindings/WallPrefabBinding";
registerBehaviourClass(AnimationRenderer);
registerBehaviourClass(AudioBehaviour);
registerBehaviourClass(Binding);
registerBehaviourClass(BitmapRenderer);
registerBehaviourClass(BoxCollider);
registerBehaviourClass(Camera);
registerBehaviourClass(CapsuleCollider);
registerBehaviourClass(CircleCollider);
registerBehaviourClass(EdgeCollider);
registerBehaviourClass(PhysicsWorld);
registerBehaviourClass(RigidBody);
registerBehaviourClass(ShapeRectRenderer);
registerBehaviourClass(TextRenderer);
registerBehaviourClass(Transform);
registerBehaviourClass(Attackable);
registerBehaviourClass(DiedMenuStateMachine);
registerBehaviourClass(Enemy);
registerBehaviourClass(Enemy1);
registerBehaviourClass(Enemy1HealthStateMachine);
registerBehaviourClass(Enemy2);
registerBehaviourClass(Enemy2HealthStateMachine);
registerBehaviourClass(Enemy3);
registerBehaviourClass(Enemy3HealthStateMachine);
registerBehaviourClass(Enemy4);
registerBehaviourClass(Enemy4HealthStateMachine);
registerBehaviourClass(Enemy5);
registerBehaviourClass(Enemy5HealthStateMachine);
registerBehaviourClass(Enemy6);
registerBehaviourClass(Enemy6HealthStateMachine);
registerBehaviourClass(EnemyHealthStateMachine);
registerBehaviourClass(GameManager);
registerBehaviourClass(HealthStateMachine);
registerBehaviourClass(MainMenuStateMachine);
registerBehaviourClass(ManaStateMachine);
registerBehaviourClass(PauseMenuStateMachine);
registerBehaviourClass(StarCollisionHandler);
registerBehaviourClass(Walkable);
registerBehaviourClass(Binding);
registerBehaviourClass(BlockPrefabBinding);
registerBehaviourClass(Enemy1PrefabBinding);
registerBehaviourClass(Enemy2PrefabBinding);
registerBehaviourClass(Enemy3PrefabBinding);
registerBehaviourClass(Enemy4PrefabBinding);
registerBehaviourClass(Enemy5PrefabBinding);
registerBehaviourClass(Enemy6PrefabBinding);
registerBehaviourClass(EnemyPrefabBinding);
registerBehaviourClass(MainRolePrefabBinding);
registerBehaviourClass(MaoQiPrefabBinding);
registerBehaviourClass(WallPrefabBinding);
const engine = new GameEngine();
engine.start();
