import { registerBehaviourClass, AnimationRenderer, BitmapRenderer, BoxCollider, Camera, CapsuleCollider, CircleCollider, EdgeCollider, PhysicsWorld, RigidBody, ShapeRectRenderer, TextRenderer, Transform, GameEngine } from "../lib/mygameengine";
import { Walkable } from "./behaviours/Walkable";
import { BlockPrefabBinding } from "./bindings/BlockPrefabBinding";
import { MainRolePrefabBinding } from "./bindings/MainRolePrefabBinding";
import { WallPrefabBinding } from "./bindings/WallPrefabBinding";
registerBehaviourClass(AnimationRenderer);
registerBehaviourClass(BitmapRenderer);
registerBehaviourClass(BoxCollider);
registerBehaviourClass(Camera);
registerBehaviourClass(CapsuleCollider);
registerBehaviourClass(CircleCollider);
registerBehaviourClass(EdgeCollider);
registerBehaviourClass(PhysicsWorld);
registerBehaviourClass(RigidBody);
registerBehaviourClass(ShapeRectRenderer);
registerBehaviourClass(TextRenderer);
registerBehaviourClass(Transform);
registerBehaviourClass(Walkable);
registerBehaviourClass(BlockPrefabBinding);
registerBehaviourClass(MainRolePrefabBinding);
registerBehaviourClass(WallPrefabBinding);
const engine = new GameEngine();
engine.start();
